# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiOSAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'TunnelKit'
  # Pods for DiOSAPP

  target 'DiOSAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiOSAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end
target 'DiOSAPP_Extension' do
  use_frameworks!

        pod 'TunnelKit'
    end

end
